const fs = require('fs');
const path = require('path');
const config = require('../config');

const DEFAULT_EXPIRE = '1893456000';

function getCookieFilePath() {
  if (process.env.BILI_COOKIES_PATH) {
    return path.resolve(process.env.BILI_COOKIES_PATH);
  }
  return path.join(config.uploadBasePath, 'cookies', 'bili_cookies.txt');
}

function ensureCookieDir() {
  const dir = path.dirname(getCookieFilePath());
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

/** 浏览器 F12 / document.cookie 格式：key=value; key=value */
function isBrowserCookieString(text) {
  const raw = String(text || '').trim();
  if (!raw || !raw.includes('=')) return false;
  if (/Netscape HTTP Cookie File/i.test(raw)) return false;
  if (/\tTRUE\t/i.test(raw) && /\.bilibili\.com/i.test(raw)) return false;
  return raw.includes(';') || /^SESSDATA=/i.test(raw) || /\bSESSDATA=/i.test(raw);
}

function parseBrowserCookieString(raw) {
  const pairs = [];
  for (const part of String(raw).split(';')) {
    const seg = part.trim();
    if (!seg) continue;
    const eq = seg.indexOf('=');
    if (eq <= 0) continue;
    const name = seg.slice(0, eq).trim();
    const value = seg.slice(eq + 1).trim();
    if (name) pairs.push({ name, value });
  }
  return pairs;
}

function browserCookieStringToNetscape(raw) {
  const pairs = parseBrowserCookieString(raw);
  if (!pairs.length) {
    throw new Error('无法解析 Cookie 字符串，请确认格式为 key=value; key=value');
  }

  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by SkitDemo admin',
  ];

  for (const { name, value } of pairs) {
    lines.push(`.bilibili.com\tTRUE\t/\tFALSE\t${DEFAULT_EXPIRE}\t${name}\t${value}`);
  }

  return `${lines.join('\n')}\n`;
}

function netscapeToBrowserString(text) {
  const pairs = [];
  for (const line of String(text).split('\n')) {
    if (!line || line.startsWith('#')) continue;
    const cols = line.split('\t');
    if (cols.length >= 7 && cols[5]) {
      pairs.push(`${cols[5]}=${cols[6] ?? ''}`);
    }
  }
  return pairs.length ? pairs.join('; ') : '';
}

function normalizeCookieText(raw) {
  let text = String(raw || '').trim();
  if (!text) return '';

  if (isBrowserCookieString(text)) {
    return browserCookieStringToNetscape(text);
  }

  // Netscape 扩展单行粘贴时补回换行
  if (!text.includes('\n') && text.includes('.bilibili.com')) {
    text = text.replace(/\s+(\.(?:www\.)?bilibili\.com\s)/g, '\n$1');
    text = text.replace(/# /g, '\n# ').trim();
  }

  if (!text.startsWith('# Netscape HTTP Cookie File')) {
    text = `# Netscape HTTP Cookie File\n# Generated by SkitDemo admin\n${text}`;
  }

  return text.replace(/\r\n/g, '\n').trim() + '\n';
}

function validateCookieText(text) {
  if (!text) {
    throw new Error('Cookie 内容不能为空');
  }
  if (!/SESSDATA/i.test(text)) {
    throw new Error('未检测到 SESSDATA，请先在浏览器登录 bilibili.com 后再复制 Cookie');
  }
  if (!/bilibili\.com/i.test(text)) {
    throw new Error('Cookie 格式异常，保存失败');
  }
}

function readCookieText() {
  const filePath = getCookieFilePath();
  if (!fs.existsSync(filePath)) return '';
  return fs.readFileSync(filePath, 'utf8');
}

function readCookieTextForDisplay() {
  const text = readCookieText();
  if (!text) return '';
  if (isBrowserCookieString(text)) return text;
  const browser = netscapeToBrowserString(text);
  return browser || text;
}

function getStatus() {
  const filePath = getCookieFilePath();
  const exists = fs.existsSync(filePath);
  const text = exists ? readCookieText() : '';
  const stat = exists ? fs.statSync(filePath) : null;

  return {
    configured: exists && text.length > 0 && /SESSDATA/i.test(text),
    file_path: filePath,
    has_sessdata: /SESSDATA/i.test(text),
    has_bilibili_domain: /bilibili\.com/i.test(text),
    updated_at: stat ? stat.mtime.toISOString() : null,
    size_bytes: stat ? stat.size : 0,
    input_format: exists && text ? 'netscape' : null,
  };
}

function saveCookieText(raw) {
  const normalized = normalizeCookieText(raw);
  validateCookieText(normalized);
  ensureCookieDir();
  fs.writeFileSync(getCookieFilePath(), normalized, 'utf8');
  return getStatus();
}

function clearCookies() {
  const filePath = getCookieFilePath();
  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath);
  }
  return getStatus();
}

function resolveReadablePath() {
  return getCookieFilePath();
}

module.exports = {
  getCookieFilePath,
  resolveReadablePath,
  getStatus,
  readCookieText,
  readCookieTextForDisplay,
  saveCookieText,
  clearCookies,
  normalizeCookieText,
  validateCookieText,
  isBrowserCookieString,
  browserCookieStringToNetscape,
  netscapeToBrowserString,
};
