const fs = require('fs');
const path = require('path');
const config = require('../config');

function getCookieFilePath() {
  if (process.env.BILI_COOKIES_PATH) {
    return path.resolve(process.env.BILI_COOKIES_PATH);
  }
  return path.join(config.uploadBasePath, 'cookies', 'bili_cookies.txt');
}

function ensureCookieDir() {
  const dir = path.dirname(getCookieFilePath());
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function normalizeCookieText(raw) {
  let text = String(raw || '').trim();
  if (!text) return '';

  // 浏览器扩展单行粘贴时补回 Netscape 换行
  if (!text.includes('\n') && text.includes('.bilibili.com')) {
    text = text.replace(/\s+(\.(?:www\.)?bilibili\.com\s)/g, '\n$1');
    text = text.replace(/# /g, '\n# ').trim();
  }

  if (!text.startsWith('# Netscape HTTP Cookie File')) {
    text = `# Netscape HTTP Cookie File\n# Generated by SkitDemo admin\n${text}`;
  }

  return text.replace(/\r\n/g, '\n').trim() + '\n';
}

function validateCookieText(text) {
  if (!text) {
    throw new Error('Cookie 内容不能为空');
  }
  if (!/bilibili\.com/i.test(text)) {
    throw new Error('未检测到 bilibili.com 域名，请确认导出的是 B 站 Cookie');
  }
  if (!/SESSDATA/i.test(text)) {
    throw new Error('未检测到 SESSDATA，请先在浏览器登录 bilibili.com 后再导出 Cookie');
  }
}

function readCookieText() {
  const filePath = getCookieFilePath();
  if (!fs.existsSync(filePath)) return '';
  return fs.readFileSync(filePath, 'utf8');
}

function getStatus() {
  const filePath = getCookieFilePath();
  const exists = fs.existsSync(filePath);
  const text = exists ? readCookieText() : '';
  const stat = exists ? fs.statSync(filePath) : null;

  return {
    configured: exists && text.length > 0 && /SESSDATA/i.test(text),
    file_path: filePath,
    has_sessdata: /SESSDATA/i.test(text),
    has_bilibili_domain: /bilibili\.com/i.test(text),
    updated_at: stat ? stat.mtime.toISOString() : null,
    size_bytes: stat ? stat.size : 0,
  };
}

function saveCookieText(raw) {
  const normalized = normalizeCookieText(raw);
  validateCookieText(normalized);
  ensureCookieDir();
  fs.writeFileSync(getCookieFilePath(), normalized, 'utf8');
  return getStatus();
}

function clearCookies() {
  const filePath = getCookieFilePath();
  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath);
  }
  return getStatus();
}

function resolveReadablePath() {
  return getCookieFilePath();
}

module.exports = {
  getCookieFilePath,
  resolveReadablePath,
  getStatus,
  readCookieText,
  saveCookieText,
  clearCookies,
  normalizeCookieText,
  validateCookieText,
};
