const fs = require('fs');
const path = require('path');
const config = require('../config');

const BILI_DOMAIN = '.bilibili.com';
const DEFAULT_EXPIRY = Math.floor(Date.now() / 1000) + 365 * 24 * 3600;

function getCookieFilePath() {
  if (process.env.BILI_COOKIES_PATH) {
    return path.resolve(process.env.BILI_COOKIES_PATH);
  }
  return path.join(config.uploadBasePath, 'cookies', 'bili_cookies.txt');
}

function ensureCookieDir() {
  const dir = path.dirname(getCookieFilePath());
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function isNetscapeCookieText(text) {
  return /# Netscape HTTP Cookie File/i.test(text)
    || /(?:^|\n)\.(?:www\.)?bilibili\.com\t/i.test(text);
}

/** 浏览器复制的一整串：buvid3=...; SESSDATA=...; bili_jct=... */
function isBrowserCookieString(text) {
  const t = String(text || '').trim();
  if (!t || t.includes('\n')) return false;
  if (isNetscapeCookieText(t)) return false;
  return /SESSDATA\s*=/i.test(t) && t.includes(';');
}

function parseBrowserCookieString(raw) {
  const pairs = [];
  const seen = new Set();

  for (const part of String(raw).split(';')) {
    const segment = part.trim();
    if (!segment) continue;
    const eq = segment.indexOf('=');
    if (eq <= 0) continue;
    const name = segment.slice(0, eq).trim();
    const value = segment.slice(eq + 1).trim();
    if (!name || seen.has(name)) continue;
    seen.add(name);
    pairs.push({ name, value });
  }

  return pairs;
}

function pairsToNetscape(pairs) {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by SkitDemo admin (browser cookie string)',
  ];

  for (const { name, value } of pairs) {
    lines.push([
      BILI_DOMAIN,
      'TRUE',
      '/',
      'FALSE',
      String(DEFAULT_EXPIRY),
      name,
      value,
    ].join('\t'));
  }

  return `${lines.join('\n')}\n`;
}

function normalizeCookieText(raw) {
  let text = String(raw || '').trim();
  if (!text) return '';

  if (isBrowserCookieString(text)) {
    const pairs = parseBrowserCookieString(text);
    if (pairs.length === 0) {
      throw new Error('无法解析 Cookie 字符串，请检查格式（name=value; name2=value2）');
    }
    return pairsToNetscape(pairs);
  }

  // Netscape 扩展单行粘贴时补回换行
  if (!text.includes('\n') && text.includes('.bilibili.com')) {
    text = text.replace(/\s+(\.(?:www\.)?bilibili\.com\s)/g, '\n$1');
    text = text.replace(/# /g, '\n# ').trim();
  }

  if (!text.startsWith('# Netscape HTTP Cookie File')) {
    text = `# Netscape HTTP Cookie File\n# Generated by SkitDemo admin\n${text}`;
  }

  return text.replace(/\r\n/g, '\n').trim() + '\n';
}

function validateCookieText(text) {
  if (!text) {
    throw new Error('Cookie 内容不能为空');
  }
  if (!/SESSDATA/i.test(text)) {
    throw new Error('未检测到 SESSDATA，请先在浏览器登录 bilibili.com 后再复制 Cookie');
  }
  if (!/bilibili\.com/i.test(text) && !/\tSESSDATA\t/i.test(text)) {
    throw new Error('Cookie 格式无效');
  }
}

function netscapeToBrowserString(text) {
  const pairs = [];
  const seen = new Set();

  for (const line of String(text || '').split('\n')) {
    const row = line.trim();
    if (!row || row.startsWith('#')) continue;
    const cols = row.split('\t');
    if (cols.length < 7) continue;
    const name = cols[5]?.trim();
    const value = cols.slice(6).join('\t').trim();
    if (!name || seen.has(name)) continue;
    seen.add(name);
    pairs.push(`${name}=${value}`);
  }

  return pairs.join('; ');
}

function readCookieText() {
  const filePath = getCookieFilePath();
  if (!fs.existsSync(filePath)) return '';
  return fs.readFileSync(filePath, 'utf8');
}

/** 管理端回显：优先浏览器整串格式，便于用户再次编辑 */
function readCookieTextForDisplay() {
  const text = readCookieText();
  if (!text) return '';
  if (isBrowserCookieString(text)) return text.trim();
  if (isNetscapeCookieText(text)) {
    const browser = netscapeToBrowserString(text);
    if (browser) return browser;
  }
  return text.trim();
}

function getStatus() {
  const filePath = getCookieFilePath();
  const exists = fs.existsSync(filePath);
  const text = exists ? readCookieText() : '';
  const stat = exists ? fs.statSync(filePath) : null;

  return {
    configured: exists && text.length > 0 && /SESSDATA/i.test(text),
    file_path: filePath,
    has_sessdata: /SESSDATA/i.test(text),
    has_bilibili_domain: /bilibili\.com/i.test(text),
    updated_at: stat ? stat.mtime.toISOString() : null,
    size_bytes: stat ? stat.size : 0,
  };
}

function saveCookieText(raw) {
  const normalized = normalizeCookieText(raw);
  validateCookieText(normalized);
  ensureCookieDir();
  fs.writeFileSync(getCookieFilePath(), normalized, 'utf8');
  return getStatus();
}

function clearCookies() {
  const filePath = getCookieFilePath();
  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath);
  }
  return getStatus();
}

function resolveReadablePath() {
  return getCookieFilePath();
}

module.exports = {
  getCookieFilePath,
  resolveReadablePath,
  getStatus,
  readCookieText,
  readCookieTextForDisplay,
  saveCookieText,
  clearCookies,
  normalizeCookieText,
  validateCookieText,
  isBrowserCookieString,
  parseBrowserCookieString,
};
